# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f497f55f560b5afb431e3da3d465e8147121d70bae2cf5eee0b85d7f8dad08f6a105ed9b863a35eb60b171ac1438ffbd38f790fd3ee06b71f3d851fa6c11d22

test:
  secret_key_base: 8219e69dd0f88506684c2d52280a89704a1413b623389c2c02c9f27011d460340cfa09ecf562e853564295e44309110cdfad096a13045c159cdc383109c71658

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  elastic_search_url: http://localhost:9200
